version: "2.1"
services:
  wireguard_server:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard_server
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=auto #optional
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      net:
        ipv4_address: 162.10.10.2

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 9123:9123
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    network_mode: "host" 

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 162.10.10.0/24
          gateway: 162.10.10.1
    driver_opts:
      com.docker.network.bridge.name: wireguard_net
